/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.def;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-06-27")
public class TApiParams implements org.apache.thrift.TBase<TApiParams, TApiParams._Fields>, java.io.Serializable, Cloneable, Comparable<TApiParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TApiParams");

  private static final org.apache.thrift.protocol.TField DATA_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("dataType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PARAMS_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("paramsData", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EXPECTED_RETURN_DATA_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("expectedReturnDataType", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("version", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TApiParamsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TApiParamsTupleSchemeFactory();

  /**
   * 
   * @see TDataEncodingType
   */
  public TDataEncodingType dataType; // optional
  public java.nio.ByteBuffer paramsData; // optional
  /**
   * 
   * @see TDataEncodingType
   */
  public TDataEncodingType expectedReturnDataType; // optional
  public int version; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see TDataEncodingType
     */
    DATA_TYPE((short)1, "dataType"),
    PARAMS_DATA((short)2, "paramsData"),
    /**
     * 
     * @see TDataEncodingType
     */
    EXPECTED_RETURN_DATA_TYPE((short)3, "expectedReturnDataType"),
    VERSION((short)4, "version");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATA_TYPE
          return DATA_TYPE;
        case 2: // PARAMS_DATA
          return PARAMS_DATA;
        case 3: // EXPECTED_RETURN_DATA_TYPE
          return EXPECTED_RETURN_DATA_TYPE;
        case 4: // VERSION
          return VERSION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VERSION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.DATA_TYPE,_Fields.PARAMS_DATA,_Fields.EXPECTED_RETURN_DATA_TYPE,_Fields.VERSION};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATA_TYPE, new org.apache.thrift.meta_data.FieldMetaData("dataType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TDataEncodingType.class)));
    tmpMap.put(_Fields.PARAMS_DATA, new org.apache.thrift.meta_data.FieldMetaData("paramsData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.EXPECTED_RETURN_DATA_TYPE, new org.apache.thrift.meta_data.FieldMetaData("expectedReturnDataType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TDataEncodingType.class)));
    tmpMap.put(_Fields.VERSION, new org.apache.thrift.meta_data.FieldMetaData("version", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TApiParams.class, metaDataMap);
  }

  public TApiParams() {
    this.dataType = thrift.def.TDataEncodingType.JSON_STRING;

    this.expectedReturnDataType = thrift.def.TDataEncodingType.JSON_STRING;

    this.version = 1;

  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TApiParams(TApiParams other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDataType()) {
      this.dataType = other.dataType;
    }
    if (other.isSetParamsData()) {
      this.paramsData = org.apache.thrift.TBaseHelper.copyBinary(other.paramsData);
    }
    if (other.isSetExpectedReturnDataType()) {
      this.expectedReturnDataType = other.expectedReturnDataType;
    }
    this.version = other.version;
  }

  public TApiParams deepCopy() {
    return new TApiParams(this);
  }

  @Override
  public void clear() {
    this.dataType = thrift.def.TDataEncodingType.JSON_STRING;

    this.paramsData = null;
    this.expectedReturnDataType = thrift.def.TDataEncodingType.JSON_STRING;

    this.version = 1;

  }

  /**
   * 
   * @see TDataEncodingType
   */
  public TDataEncodingType getDataType() {
    return this.dataType;
  }

  /**
   * 
   * @see TDataEncodingType
   */
  public TApiParams setDataType(TDataEncodingType dataType) {
    this.dataType = dataType;
    return this;
  }

  public void unsetDataType() {
    this.dataType = null;
  }

  /** Returns true if field dataType is set (has been assigned a value) and false otherwise */
  public boolean isSetDataType() {
    return this.dataType != null;
  }

  public void setDataTypeIsSet(boolean value) {
    if (!value) {
      this.dataType = null;
    }
  }

  public byte[] getParamsData() {
    setParamsData(org.apache.thrift.TBaseHelper.rightSize(paramsData));
    return paramsData == null ? null : paramsData.array();
  }

  public java.nio.ByteBuffer bufferForParamsData() {
    return org.apache.thrift.TBaseHelper.copyBinary(paramsData);
  }

  public TApiParams setParamsData(byte[] paramsData) {
    this.paramsData = paramsData == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(paramsData.clone());
    return this;
  }

  public TApiParams setParamsData(java.nio.ByteBuffer paramsData) {
    this.paramsData = org.apache.thrift.TBaseHelper.copyBinary(paramsData);
    return this;
  }

  public void unsetParamsData() {
    this.paramsData = null;
  }

  /** Returns true if field paramsData is set (has been assigned a value) and false otherwise */
  public boolean isSetParamsData() {
    return this.paramsData != null;
  }

  public void setParamsDataIsSet(boolean value) {
    if (!value) {
      this.paramsData = null;
    }
  }

  /**
   * 
   * @see TDataEncodingType
   */
  public TDataEncodingType getExpectedReturnDataType() {
    return this.expectedReturnDataType;
  }

  /**
   * 
   * @see TDataEncodingType
   */
  public TApiParams setExpectedReturnDataType(TDataEncodingType expectedReturnDataType) {
    this.expectedReturnDataType = expectedReturnDataType;
    return this;
  }

  public void unsetExpectedReturnDataType() {
    this.expectedReturnDataType = null;
  }

  /** Returns true if field expectedReturnDataType is set (has been assigned a value) and false otherwise */
  public boolean isSetExpectedReturnDataType() {
    return this.expectedReturnDataType != null;
  }

  public void setExpectedReturnDataTypeIsSet(boolean value) {
    if (!value) {
      this.expectedReturnDataType = null;
    }
  }

  public int getVersion() {
    return this.version;
  }

  public TApiParams setVersion(int version) {
    this.version = version;
    setVersionIsSet(true);
    return this;
  }

  public void unsetVersion() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERSION_ISSET_ID);
  }

  /** Returns true if field version is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERSION_ISSET_ID);
  }

  public void setVersionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERSION_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DATA_TYPE:
      if (value == null) {
        unsetDataType();
      } else {
        setDataType((TDataEncodingType)value);
      }
      break;

    case PARAMS_DATA:
      if (value == null) {
        unsetParamsData();
      } else {
        if (value instanceof byte[]) {
          setParamsData((byte[])value);
        } else {
          setParamsData((java.nio.ByteBuffer)value);
        }
      }
      break;

    case EXPECTED_RETURN_DATA_TYPE:
      if (value == null) {
        unsetExpectedReturnDataType();
      } else {
        setExpectedReturnDataType((TDataEncodingType)value);
      }
      break;

    case VERSION:
      if (value == null) {
        unsetVersion();
      } else {
        setVersion((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DATA_TYPE:
      return getDataType();

    case PARAMS_DATA:
      return getParamsData();

    case EXPECTED_RETURN_DATA_TYPE:
      return getExpectedReturnDataType();

    case VERSION:
      return getVersion();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DATA_TYPE:
      return isSetDataType();
    case PARAMS_DATA:
      return isSetParamsData();
    case EXPECTED_RETURN_DATA_TYPE:
      return isSetExpectedReturnDataType();
    case VERSION:
      return isSetVersion();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TApiParams)
      return this.equals((TApiParams)that);
    return false;
  }

  public boolean equals(TApiParams that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_dataType = true && this.isSetDataType();
    boolean that_present_dataType = true && that.isSetDataType();
    if (this_present_dataType || that_present_dataType) {
      if (!(this_present_dataType && that_present_dataType))
        return false;
      if (!this.dataType.equals(that.dataType))
        return false;
    }

    boolean this_present_paramsData = true && this.isSetParamsData();
    boolean that_present_paramsData = true && that.isSetParamsData();
    if (this_present_paramsData || that_present_paramsData) {
      if (!(this_present_paramsData && that_present_paramsData))
        return false;
      if (!this.paramsData.equals(that.paramsData))
        return false;
    }

    boolean this_present_expectedReturnDataType = true && this.isSetExpectedReturnDataType();
    boolean that_present_expectedReturnDataType = true && that.isSetExpectedReturnDataType();
    if (this_present_expectedReturnDataType || that_present_expectedReturnDataType) {
      if (!(this_present_expectedReturnDataType && that_present_expectedReturnDataType))
        return false;
      if (!this.expectedReturnDataType.equals(that.expectedReturnDataType))
        return false;
    }

    boolean this_present_version = true && this.isSetVersion();
    boolean that_present_version = true && that.isSetVersion();
    if (this_present_version || that_present_version) {
      if (!(this_present_version && that_present_version))
        return false;
      if (this.version != that.version)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDataType()) ? 131071 : 524287);
    if (isSetDataType())
      hashCode = hashCode * 8191 + dataType.getValue();

    hashCode = hashCode * 8191 + ((isSetParamsData()) ? 131071 : 524287);
    if (isSetParamsData())
      hashCode = hashCode * 8191 + paramsData.hashCode();

    hashCode = hashCode * 8191 + ((isSetExpectedReturnDataType()) ? 131071 : 524287);
    if (isSetExpectedReturnDataType())
      hashCode = hashCode * 8191 + expectedReturnDataType.getValue();

    hashCode = hashCode * 8191 + ((isSetVersion()) ? 131071 : 524287);
    if (isSetVersion())
      hashCode = hashCode * 8191 + version;

    return hashCode;
  }

  @Override
  public int compareTo(TApiParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDataType()).compareTo(other.isSetDataType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDataType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dataType, other.dataType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetParamsData()).compareTo(other.isSetParamsData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParamsData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paramsData, other.paramsData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetExpectedReturnDataType()).compareTo(other.isSetExpectedReturnDataType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpectedReturnDataType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expectedReturnDataType, other.expectedReturnDataType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetVersion()).compareTo(other.isSetVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version, other.version);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TApiParams(");
    boolean first = true;

    if (isSetDataType()) {
      sb.append("dataType:");
      if (this.dataType == null) {
        sb.append("null");
      } else {
        sb.append(this.dataType);
      }
      first = false;
    }
    if (isSetParamsData()) {
      if (!first) sb.append(", ");
      sb.append("paramsData:");
      if (this.paramsData == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.paramsData, sb);
      }
      first = false;
    }
    if (isSetExpectedReturnDataType()) {
      if (!first) sb.append(", ");
      sb.append("expectedReturnDataType:");
      if (this.expectedReturnDataType == null) {
        sb.append("null");
      } else {
        sb.append(this.expectedReturnDataType);
      }
      first = false;
    }
    if (isSetVersion()) {
      if (!first) sb.append(", ");
      sb.append("version:");
      sb.append(this.version);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TApiParamsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TApiParamsStandardScheme getScheme() {
      return new TApiParamsStandardScheme();
    }
  }

  private static class TApiParamsStandardScheme extends org.apache.thrift.scheme.StandardScheme<TApiParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TApiParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATA_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.dataType = thrift.def.TDataEncodingType.findByValue(iprot.readI32());
              struct.setDataTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PARAMS_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.paramsData = iprot.readBinary();
              struct.setParamsDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXPECTED_RETURN_DATA_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.expectedReturnDataType = thrift.def.TDataEncodingType.findByValue(iprot.readI32());
              struct.setExpectedReturnDataTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.version = iprot.readI32();
              struct.setVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TApiParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dataType != null) {
        if (struct.isSetDataType()) {
          oprot.writeFieldBegin(DATA_TYPE_FIELD_DESC);
          oprot.writeI32(struct.dataType.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.paramsData != null) {
        if (struct.isSetParamsData()) {
          oprot.writeFieldBegin(PARAMS_DATA_FIELD_DESC);
          oprot.writeBinary(struct.paramsData);
          oprot.writeFieldEnd();
        }
      }
      if (struct.expectedReturnDataType != null) {
        if (struct.isSetExpectedReturnDataType()) {
          oprot.writeFieldBegin(EXPECTED_RETURN_DATA_TYPE_FIELD_DESC);
          oprot.writeI32(struct.expectedReturnDataType.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetVersion()) {
        oprot.writeFieldBegin(VERSION_FIELD_DESC);
        oprot.writeI32(struct.version);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TApiParamsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TApiParamsTupleScheme getScheme() {
      return new TApiParamsTupleScheme();
    }
  }

  private static class TApiParamsTupleScheme extends org.apache.thrift.scheme.TupleScheme<TApiParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TApiParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDataType()) {
        optionals.set(0);
      }
      if (struct.isSetParamsData()) {
        optionals.set(1);
      }
      if (struct.isSetExpectedReturnDataType()) {
        optionals.set(2);
      }
      if (struct.isSetVersion()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetDataType()) {
        oprot.writeI32(struct.dataType.getValue());
      }
      if (struct.isSetParamsData()) {
        oprot.writeBinary(struct.paramsData);
      }
      if (struct.isSetExpectedReturnDataType()) {
        oprot.writeI32(struct.expectedReturnDataType.getValue());
      }
      if (struct.isSetVersion()) {
        oprot.writeI32(struct.version);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TApiParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.dataType = thrift.def.TDataEncodingType.findByValue(iprot.readI32());
        struct.setDataTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.paramsData = iprot.readBinary();
        struct.setParamsDataIsSet(true);
      }
      if (incoming.get(2)) {
        struct.expectedReturnDataType = thrift.def.TDataEncodingType.findByValue(iprot.readI32());
        struct.setExpectedReturnDataTypeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.version = iprot.readI32();
        struct.setVersionIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

