/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.def;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TDataEncodingType implements org.apache.thrift.TEnum {
  JSON_STRING(0),
  JSON_GZIP(1);

  private final int value;

  private TDataEncodingType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TDataEncodingType findByValue(int value) { 
    switch (value) {
      case 0:
        return JSON_STRING;
      case 1:
        return JSON_GZIP;
      default:
        return null;
    }
  }
}
